name: Run-Escrity

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Ejecutar script de Python
      run: python main.py
