name: Testing code interpreter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile
      run: |
        cd src
        if [ -f "main.c" ]; then
          echo "Compiling. . ."
          clang -o main main.c
          if [ $? -ne 0 ]; then
            echo "Error: Compilation failed for main.c"
            exit 1
          fi
        else
          echo "Error: main.c not found in src directory"
          exit 1
        fi

    - name: Run
      run: |
        cd src
        if [ -x "main" ]; then
          echo "Running. . ."
          ./main
          if [ $? -ne 0 ]; then
            echo "Error: Execution failed for main"
            exit 1
          fi
        else
          echo "Error: main executable not found"
          exit 1
        fi 
